### PR TITLE
Update R and Py Dockerfiles

### LINKED ISSUE #39: Allow keyboard shortcuts on instructor image
Allow keyboard shortcuts X,C,V,Shift-M, etc. on the instructor image which are disabled on the student image.

### PR DESCRIPTION
**Pull request by briank-git**
Python:
- Update `altair` to 5.1.2
- Disable announcement pop-up on start
- Allow keyboard shortcuts on instructor image

R: 
- Install `themis` package
  -  Tested loading both `themis` and `tidyclust` in an R notebook, appears to have no conflicts
- Disable announcement pop-up on start
- Allow keyboard shortcuts on instructor image

Fixes #39

### CODE REVIEW

**Comment by joelostblom** [comment]
Thanks @briank-git ! Note that altair should update to 5.3 if we lift the version requirement since that is the latest version of conda (which would be great because there are some nice updates since 5.1.2). We also [made the installation process more convenient](https://altair-viz.github.io/getting_started/installation.html) so you should be able to just install `altair-all` and get rid of the line installing vl-convert and vegafusion separately

**Comment by briank-git** [comment]
@joelostblom Thanks Joel for the quick feedback! That's great that there's an `altair-all` package to install those dependencies, I've added it to the Dockerfile. 

I also want to ask if there's still a reason for us to pin `pandas<2.1`? It seems the build fails unless I remove that pin and allow `pandas` version 2.1.1 to install

**Comment by trevorcampbell** [comment]
@briank-git @joelostblom re `pandas<2.1`, I don't quite recall, but it may have something to do with getting the various viz package versions to work out all together

But as long as you run through all the worksheets and tutorials and they all work properly still, we can safely make the update.

**Comment by briank-git** [comment]
Thanks @trevorcampbell, I ran the image with `pandas==2.1.1` on all of the Py source notebooks and they run fine. I also ran the new R image on all the R source notebooks as well. 

I'll merge the PR later today in case there's any other comments.

**Comment by joelostblom** [comment]
> I also want to ask if there's still a reason for us to pin pandas<2.1? 

I think it initially was there to silence a deprecation warning via altair, but that has since been fixed and we don't pin it in altair either so should be fine.

> (also, great job removing that announcement! so annoying to have to click "no" every time it started)

Agreed

**Review by joelostblom — APPROVED** [review]

**Pull request merged**
